# Generated by Django 5.2.12 on 2026-03-13 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sleeppredictionrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SleepPredictionRecord',
        ),
    ]
