# Generated by Django 5.2.12 on 2026-03-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_predictor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleeppredictionrecord',
            name='bmi_category',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleeppredictionrecord',
            name='bp_systolic',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleeppredictionrecord',
            name='heart_rate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleeppredictionrecord',
            name='physical_activity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleeppredictionrecord',
            name='sleep_quality',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sleeppredictionrecord',
            name='stress_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
