# Generated by Django 5.2.12 on 2026-03-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sleep_predictor', '0002_sleeppredictionrecord_bmi_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleeppredictionrecord',
            name='shap_explanation',
            field=models.TextField(blank=True, null=True),
        ),
    ]
